---
title: "CovidVaccineApprovalOnlyPartThreeFinal"
author: "Felipe Castillo"
date: "8/12/2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
bibliography: bibliography.bib
---

<b> <font size="4"> Introduction</font></b> \

The focus of my study was to see two things. Are the number of flu cases relatable to covid cases in regards to the vaccine acceptance? Also, are the vaccine approvals based on a states political standing? 
Over the past year and a half, we've been affected by a virus that has changed the world forever. Over the past few months, we have seen both a divide in people going to get the COVID vaccine and others who have refused to take it. However, are these reactions new or could past history predict the outcome? Even if the outcome could not have been predicted, maybe we can find a correlation in the data. The information is important for both political and medical reasons. On the political side, it could help with their approvals. On the medical side, we could determine how many vaccine shots to get. At this point, there are way more covid vaccinations than people taking them.



<b> <font size="4">The problem statement you addressed</font></b> \

Recently, we have been given a choice to either take the vaccine or not. The reality is that some people dislike that choice. Some people want the vaccine to be mandatory. Others dislike the idea of taking the vaccine. Work places are starting to make it a requirement to keep employment. Law suits are being filed with people that do not want to take it. With growing concerns over the new variants, the status quo doesn't seem to change. The hypothesis is that this is due to political standing inside the states. Meaning that in a red state people are more likely to not take the vaccine and be strongly opposed to mandatory influences. The blue states, however, are more likely to take the vaccine and be open to mandatory vaccines. The example I gave was comparing states like Texas, a confirmed red state, with California, a confirmed blue state. The most shocking question is could these results have been predicted with past vaccine results. For instance, could we say that in the future, red states are more likely to refuse a vaccine? 



<b> <font size="4">How you addressed this problem statement</font></b> \

First, I wanted to check if there were similar numbers between the influenza and covid vaccines. This would explain if perhaps the past could have predicted the future. In other words, if the number of people that got the flu vaccine are similar to those that got the covid vaccine, could there be a predictor variable used for the next wave of the virus? So the data that was used was from a USA population that was fully vaccinated for the flu and one for a USA population that had the covid vaccine. The overall results of the two data points were analyzed. Next, I used a political data point to classify the states based on their electoral choice for presidential election. Doing this allowed me to see if the states lean more left or more right. The states were classified as blue or red. Once the data was classified, I combined the political data frame with the covid results based on state so I could tell which state results leaned more left or more right. Once the data was combined, I posted a view graph that showed which classification had the most vaccine shots. After that, five states were randomly picked and checked by their political standing to see if the hypothesis held true. 

<b> <font size="4">Analysis</font></b> \

The fully vaccinated population for covid and the fully vaccinated population for the flu were very close. In fact, the covid vaccine had 164 million vaccinated people while the flu vaccine had 174 million. When you count the partially and fully vaccinated people, you have 190 million. The count is quite different if we count those people as well. So what is needed is for a whole year to be analyzed instead of just a couple of months to have a better idea of the complete total. In the political analyses, there were more democratic states than there were republican states. In other words, there were more blue states than red states. This would make complete sense due to the fact that we have a democratic president. So the hypothesis is that if there are more blue states, there will be more vaccinated individuals. The blue states will out pace the red states in total vaccinations. The one with the largest amount of vaccinations was California, a blue state. There were a few others like Florida that had high numbers. The data was mutated by state and political affiliation. The data gave strength to the first hypothesis that blue states where indeed out pacing red states in total vaccinations. There was a large margin which can give light to a political divide. The five states that were looked at were 3 red states and 2 blue states. I took the five states total vaccinations. However,the data of total vaccinations was based off of doses and not actual people. The data suggested that the doses were based off of two shots. All the data had almost double of its total population. I divided all the vaccinations total by two. With what was left, I divided it by the total population of the state. That result was then turned into a percentage and the percentage aligned with their political standing. California was not even close. The real question is if partial vaccinations count. The result for Florida might be an outlier. I based these values off of fully vaccination data. 


<b> <font size="4">Implications</font></b> \

There are a few implications. One is that it could have been a possibility to predict covid vaccine approval ratings using the flu vaccine approval. More data is needed to support this correlation, but the data does seem to show a similarity between the two vaccines. Also, it seems that political affiliation does hold some weight over vaccine approval. That means if the red states accepted the vaccine, there would be a large number of people getting the vaccine. This data is important because we can figure out how people will react in case there is another vaccine. Let's say that the delta variant mutates to a more aggressive strain that our vaccine cannot protect against. If another vaccine is made, we could distribute the vaccine where the people would actually use it and not where it will go unused. Right now, the United States has more doses of the vaccine than what the people are actually taking. Overall, it seems that politics has some weight over vaccination results.


<b> <font size="4">Limitations</font></b> \


I can think of so many limitations. The first is looking at mandatory vaccination history. It seems that some companies and even the government are pushing towards mandatory vaccination. How would this reflect in the data? Even if we use a predictor model to suggest that there might be a virus like the flu that we can base off of, the total dynamic of this past data could be used. In theory, a lot more people would probably get it. The data also does not show if there is currently any pressure from the states to get the vaccine. Take California for example. They have pushed the vaccine harder and the numbers are the highest in the state. But then again, it would reinforce the original claim that states hold barring on the results.

The other limitation is knowing age. Perhaps there was better data to explain age. I would be interested to see people from the age of 18 and older. There are also news reports that suggest that some kids under a certain age cannot get the vaccine. This would show if the numbers are skewed or if there are missing results. Perhaps this can explain why the fully vaccinated flu population was more than the covid vaccinations.


Another limitation is to see if there is something other then the states causing it. Perhaps people are watching a certain media station that persuades them. The correlation to state politics can be met, but it cannot be said to be the only persuading factor to covid vaccine results.

The why is still far from being found.



<b> <font size="4">Concluding Remarks</font></b> \


Overall, the project was fun. It gave me a lot of insight to real data science techniques. What they say is true that 80% of my time was spent cleaning and rearranging data. The problem with a lot of data that I found was that there was a lot of noise. A lot of the values that were in the data sets did not even make sense. In fact, regarding state information, it took me a while to realize that the vaccine was counted in doses and not people. The graphs that were built were interactive and gave a lot of information. I can say I will leave this class with a whole lot more skills then when I came in.





<b> <font size="4"> Citation</font></b> \

[@PoliticalTracker] \
[@FLUBYUSA] \
[@OWDFLUBYUSA] \
[@CDCSTATEVACCINATIONS] \
[@CDCCOVIDBYCOUNTRIES] \
[@CDCCOVIDBYSTATE]  

